# Generated by Django 5.1.4 on 2025-01-06 11:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("ticket_link", models.URLField(blank=True, null=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("upcoming", "Upcoming"),
                            ("past", "Past"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
